name: Deploy to gh-pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install submodules
              run: git submodule update --init --recursive

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'npm'

            - name: Install dependencies
              run: npm update --legacy-peer-deps

            - name: Build application
              run: npm run build

            - name: Deploy application
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.MY_TOKEN }}
                  publish_dir: ./dist
